### ISSUE TITLE
"Youtube Folder Not Found"

### ISSUE THREAD

**Issue by AddoSolutions** [xinmans/tubearchivist-emby#1]
Not sure why I am getting this, not a python expert by any means, but I believe I am all set here, but keep getting this error:

```
[root@X tubearchivist-emby]# docker-compose run --rm tubearchivist-emby bash
Creating tubearchivist-emby_tubearchivist-emby_run ... done

root@313151e5730b:/app# ls /youtube/
UC-4ZFgxxxxxx_fogdxxxxxx  UCFh3dxxxxxxx-Cdxxxx  ...redacted

root@313151e5730b:/app# python main.py
[connection] verified emby connection
[connection] verified tube archivist connection
Traceback (most recent call last):
  File "/app/main.py", line 18, in <module>
    main()
  File "/app/main.py", line 13, in main
    library = Library()
              ^^^^^^^^^
  File "/app/src/series.py", line 35, in __init__
    self.yt_collection: str = self.get_yt_collection()
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/series.py", line 52, in get_yt_collection
    raise ValueError("youtube folder not found")
ValueError: youtube folder not found

root@313151e5730b:/app#
```

Any idea what's up here?

**Comment by xinmans** [comment]
> series

just show me your docker-compose.yml

**Comment by AddoSolutions** [comment]
```

version: '3.3'

services:
  tubearchivist-emby:
    restart: always
    build: .
    container_name: tubearchivist-emby
    user: 0:0
    privileged: true
    environment:
      - HOST_UID=0
      - HOST_GID=0
      - TA_URL=http://1.2.3.4:8000
      - TA_TOKEN=xxyyzz
      - JF_URL=https://my.emby.server:1234
      - JF_TOKEN=xxyyzz
      - JF_FOLDER=MyFolder
    volumes:
      - ./logs:/app/logs
      - /usr/share/zoneinfo/America/New_York:/etc/localtime
      - /path/to/my/folder:/youtube  # matching youtube volume as in Tube Archivist，volumes mount point must to be youtube
    ports:
      - 8002:8001
    expose:
      - "8001"

```

**Comment by xinmans** [comment]
```
       def get_yt_collection(self) -> str:
        """get collection id for youtube folder"""
        path: str = "Items?Recursive=true&includeItemTypes=Folder"
        folders: dict = Jellyfin().get(path)
        folder_name: str | None = get_config()["jf_folder"]

        if not folder_name or len(folder_name) < 1:
            folder_name = "youtube"
        else:
            folder_name = folder_name.lower()

        for folder in folders["Items"]:
            if folder.get("Name").lower() == folder_name:
                return folder.get("Id")

        raise ValueError("youtube folder not found")
```
the youtube folder will compare with the folder in emby
have you set emby folder in tv show？

please follow https://github.com/xinmans/tubearchivist-emby/blob/main/README.md to set it before run main.py

Setup emby
Take a look at the example docker-compose.yml provided.

Add the Tube Archivist /youtube folder as a media folder for emby.

IMPORTANT: This needs to be mounted as read only aka ro, otherwise this will mess up Tube Archivist.
Add a new media library to your emby server for your Tube Archivist videos, required options:

Content type: Shows
Displayname: YouTube
Folder: Root folder for Tube Archivist videos
Deactivate all Metadata downloaders
Automatically refresh metadata from the internet: Never
Deactivate all Image fetchers
Let emby complete the library scan

This works best if emby has found all media files and Tube Archivist isn't currently downloading.
At first, this will add all channels as a Show with a single Season Unknown.
Then this script will populate the metadata.
Backdrops

In your emby installation under > Settings > Display > enable Backdrops for best channel art viewing experience.

**Comment by AddoSolutions** [comment]
Getting further! I thought the JF_FOLDER was the "name" of the library in Emby. Renamed to "YouTube" and am getting further.

New error:

```
[root@container1 tubearchivist-emby]# docker-compose run --rm tubearchivist-emby python main.py
Creating tubearchivist-emby_tubearchivist-emby_run ... done
[connection] verified emby connection
[connection] verified tube archivist connection
Traceback (most recent call last):
  File "/app/main.py", line 18, in <module>
    main()
  File "/app/main.py", line 14, in main
    library.validate_series()
  File "/app/src/series.py", line 57, in validate_series
    self.refresh_collection(collection_id)
  File "/app/src/series.py", line 106, in refresh_collection
    if folder["RefreshStatus"] == "Idle":
       ~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'RefreshStatus'
ERROR: 1
```

Any idea what that is about?

**Comment by AddoSolutions** [comment]
I am not quite sure what this does, but I commented out the following and bumped up the `return` and it seems to be doing the job now.

https://github.com/xinmans/tubearchivist-emby/blob/main/app/src/series.py#L106

I do get this from Emby though...

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.25.4</center>
</body>
</html>
```

**Comment by xinmans** [comment]
> I am not quite sure what this does, but I commented out the following and bumped up the `return` and it seems to be doing the job now.
> 
> https://github.com/xinmans/tubearchivist-emby/blob/main/app/src/series.py#L106
> 
> I do get this from Emby though...
> 
> ```
> <html>
> <head><title>413 Request Entity Too Large</title></head>
> <body>
> <center><h1>413 Request Entity Too Large</h1></center>
> <hr><center>nginx/1.25.4</center>
> </body>
> </html>
> ```

maybe the resource of the server  which your emby running is not enough

**Comment by xinmans** [comment]
> > I am not quite sure what this does, but I commented out the following and bumped up the `return` and it seems to be doing the job now.
> > https://github.com/xinmans/tubearchivist-emby/blob/main/app/src/series.py#L106
> > I do get this from Emby though...
> > ```
> > <html>
> > <head><title>413 Request Entity Too Large</title></head>
> > <body>
> > <center><h1>413 Request Entity Too Large</h1></center>
> > <hr><center>nginx/1.25.4</center>
> > </body>
> > </html>
> > ```
> 
> maybe the resource of the server which your emby running is not enough

you can refresh by handle in emby when first add tv show

**Comment by supertom44** [comment]
@AddoSolutions How did you get past the youtube collection folder not found?

I'm having the same issue and not sure what step I've missed.

```
version: '3.3'

services:
  tubearchivist-emby:
    restart: always
    build: .
    container_name: tubearchivist-emby
    environment:
      - TA_URL=xxx
      - TA_TOKEN=xxx
      - JF_URL=xxx
      - JF_TOKEN=xxx
      - JF_FOLDER=youtube
    volumes:
      - ./logs:/app/logs
      - /mnt/user/YouTube:/youtube
    ports:
      - 8002:8001
    expose:
      - "8001"

```

I have my emby library as such:
![image](https://github.com/xinmans/tubearchivist-emby/assets/6057877/d4404052-0ed9-48dd-a9f1-001a90df8684)

Note `/media/plex/youtube` mounts from the same as above `/mnt/user/YouTube`
